export const TRY_AUTH = 'TRY_AUTH';
export const TRY_FORGOTPASS = 'TRY_FORGOTPASS';
export const TRY_OTP = 'TRY_OTP';
export const UI_START_LOADING ='UI_START_LOADING';
export const UI_STOP_LOADING ='UI_STOP_LOADING';
export const DASHBOARD_DATA = "DASHBOARD_DATA";
export const COMPLAINTS_LIST_DATA = "COMPLAINTS_LIST_DATA";
export const CGRO_REPORT_SEARCH_DATA = "CGRO_REPORT_SEARCH_DATA";
export const CGRO_REPORT_DATA = "CGRO_REPORT_DATA";
export const COMPLAINTS_DETAILS_DATA = "COMPLAINTS_DETAILS_DATA";
export const REPLY_HISTORY_DATA = "REPLY_HISTORY_DATA";
export const CLOSE_ACTION = "CLOSE_ACTION";
export const CLOSE_REQUEST_CATEGORY = "CLOSE_REQUEST_CATEGORY";
export const COMPLAINTS_DATA = "COMPLAINTS_DATA";
export const FORWARD_LEVEL = "FORWARD_LEVEL";
export const FORWARD_TO = "FORWARD_TO";
export const CUSTOMER_LIST_DATA = "CUSTOMER_LIST_DATA";

export const MINORITY_COMMUNITY= "MINORITY_COMMUNITY";  
export const STATE_LIST= "STATE_LIST";  
export const CITY_LIST= "CITY_LIST"; 

export const AUTH_DATA = "AUTH_DATA"; 
export const TOTAL_COUNT = "TOTAL_COUNT";

export const USER_DATA = "USER_DATA";
export const ADD_COMP_USER_DATA = "ADD_COMP_USER_DATA";
export const IS_PROFILE_UPDATED = "IS_PROFILE_UPDATED";
export const SCREEN_TITLE = "SCREEN_TITLE";

export const COMPLAINT_SOURCE = "COMPLAINT_SOURCE";
export const COMPLAINT_TYPE = "COMPLAINT_TYPE";
export const GRIEVANCE_CAT = "GRIEVANCE_CAT";
export const PENSION_TYPE = "PENSION_TYPE";
export const REQUEST_CAT = "REQUEST_CAT";
export const PRODUCT_TYPE = "PRODUCT_TYPE";
export const SUB_TYPE = "SUB_TYPE";
export const BRANCH = "BRANCH";
export const CUSTOMER_DETAIL = "CUSTOMER_DETAIL";
export const CUSTOMER_COMPLAINTS = "CUSTOMER_COMPLAINTS"; 
export const CUSTOMER_COMPLAINTS_ITEM = "CUSTOMER_COMPLAINTS_ITEM";
export const BRANCH_NAME = "BRANCH_NAME";
export const SELECTED_STATE = "SELECTED_STATE";
export const SELECTED_CITY= "SELECTED_CITY";  
export const USER_ROLE= "USER_ROLE";